branches:
  - main
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - [
      "@semantic-release/github",
      {
        "assets": [
          { "path": "build/bobo-kobo.zip", "label": "Kobo build (ARM hard float)" },
          { "path": "build/bobo-desktop.zip", "label": "Desktop (Linux x86_64) build" },
        ],
        "successComment": false,
      }
    ]
  - "semantic-release-export-data"
